### ISSUE TITLE
[Bug] Ceramic bucket get converted to an iron bucket

### ISSUE THREAD

**Issue by benbenlaw** [SuperMartijn642/TrashCans#10]
**Version Info**
- Minecraft, 1.16.5
- Trash Cans, 1.0.9

**Description of the Bug**
Gives a iron bucket in a fluid trash can in stead on a ceramic one when those buckets are used

**Steps to Reproduce**
install https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket

**Screenshots**
![image](https://user-images.githubusercontent.com/42780877/117114521-df15c900-ad83-11eb-981c-1e7577abf50a.png)
![image](https://user-images.githubusercontent.com/42780877/117114541-e341e680-ad83-11eb-9803-5667a00a45fe.png)

**Comment by cech12** [comment]
I think, this line causes this issue:
https://github.com/SuperMartijn642/TrashCans/blob/c2dc6258a192a7bd0291c7447a8d85b72a832b84/src/main/java/com/supermartijn642/trashcans/TrashCanTile.java#L324

**Comment by SuperMartijn642** [comment]
Yes, it's because I check if it's an instance of the `BucketItem` class and not the actual bucket item.
https://github.com/SuperMartijn642/TrashCans/blob/c2dc6258a192a7bd0291c7447a8d85b72a832b84/src/main/java/com/supermartijn642/trashcans/TrashCanTile.java#L323

**Comment by cech12** [comment]
Doesn't the vanilla bucket have also a FluidHandler?

**Comment by SuperMartijn642** [comment]
Yes indeed, only the water bottle doesn't, so no clue why I didn't just use that.

**Comment by benbenlaw** [comment]
haha at least you found it

**Comment by SuperMartijn642** [comment]
I fixed the issue now in version 1.0.10.

Thanks to you all for reporting the issue and helping out!
