### ISSUE TITLE
[Crash] with newest version of mod

### ISSUE THREAD

**Issue by Warbringer12** [SuperMartijn642/TrashCans#11]
**Version Info**
- Minecraft, 1.16.5
- Trash Cans, 1.0.10-mc1.16.5

**Steps to Reproduce**
...1. launch minecraft

**Crash report (~/logs/latest.log)**
...
[crash-2021-05-07_18.31.42-fml.txt](https://github.com/SuperMartijn642/TrashCans/files/6444927/crash-2021-05-07_18.31.42-fml.txt)

[Uploading 2021-05-07-2.log…]()

**Comment by SuperMartijn642** [comment]
It says you don't have the core lib installed, it is required for the newest version.

**Comment by luffykick** [comment]
Same issue as OP... but for clarity... your latest trashcans update "trashcans-1.0.10-mc1.16.5" is now requiring "supermartijn642**corelib**-1.0.3-mc1.16.5" 

Many of us have "supermartijn642**configlib**-1.0.5a-mc1.16" which is where the confusion comes in... its easy to confuse config with core without paying close attention.

Might be a good idea to put that in bold on the Trashcans curseforge page to avoid confusion from OG fans.

**Comment by moon-st0ne** [comment]
why the hell does this mod require its own library mod now

**Comment by SuperMartijn642** [comment]
Because I make like 14 mods for different 5 Minecraft versions and I don't want to have to repeat the same code constantly.

**Comment by SuperMartijn642** [comment]
@Warbringer12 I assume your problem is solved now. If not, just comment here and I'll reopen the issue.
