### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by TheTechPny** [SuperMartijn642/TrashCans#12]
Sorry forgot to edit the title

**Version Info**
- Minecraft, 1.16.5
- Trash Cans, trashcans-1.0.10-mc1.16.5.jar

**Steps to Reproduce**
A player mined a trash can with an Ars Nouveau spell

"ars nouveau, so it was a custom spell
touch+break+pickup"

**Crash report (~/logs/latest.log)**
https://pastebin.com/raw/Lwu3ge5E

**Comment by SuperMartijn642** [comment]
I fixed it now in [Core Lib version 1.0.10](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib/files/all).

Thank you for the reporting the issue!
