### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by PessimisticBastard** [SuperMartijn642/TrashCans#13]
**Version Info**
1.16.5
trashcans-1.0.10-mc1.16.5.jar
Forge 36.2.2

**Steps to Reproduce**
Right click on trashcan, crashes. Might be issue with newer versions of Forge.

**Crash report (~/logs/latest.log)**

See
https://pastebin.com/VamGaLcV

**Comment by SuperMartijn642** [comment]
It seems this issue was introduced in Core lib version 1.0.11.

It *should* be fixed now in Core lib version 1.0.11a for 1.16.5.
