### ISSUE TITLE
[Bug] Create pipes dont output to liquid trash cans

### ISSUE THREAD

**Issue by MrNoe93** [SuperMartijn642/TrashCans#14]
- Minecraft 1.16.5
- Trash Cans 1.0.10
- Core lib 1.0.12
- Create 0.3.2d
- Flywheel 0.2.4

Description:
Create pipes visually attach to liquid trash cans but dont actually output their fluid into them.  They show the particles as if the pipe is connected to nothing and will waterlog the trash can if left like that (when using water as the liquid)

Recreate:
Setup a Create tank with liquid.  Pump out of the create tank into a liquid trash can via a create pipe.

Screenshots:
https://imgur.com/a/cy36Haj

**Comment by SuperMartijn642** [comment]
Sorry for the very late response. I don't have much time to work on mods currently, so I'll look into once I work on mods again.

**Comment by MrNoe93** [comment]
This appears to be fixed with a newer version of Create.  The issue was, "Fixed fluid pipes getting stuck trying to waterlog non-solid blocks with fluid handling capabilities".

**Comment by SuperMartijn642** [comment]
It indeed seems to work fine when I test it now, so I'll close the issue.

Thank you for reporting the problem!
