### ISSUE TITLE
[Feature] Please revert change of unable to void Mekanism waste and make it configurable

### ISSUE THREAD

**Issue by LuciusV** [SuperMartijn642/TrashCans#16]
**Is your feature request related to a problem? Please describe.**
In https://github.com/SuperMartijn642/TrashCans/issues/5 possibility to get rid of Mekanism waste was removed

**Describe the solution you'd like**
Could you please make it configurable instead, for people who find annoying for mess with waste in singleplayer.
Others can do not use it or turn off in multiplayer, but please restore this feature for those who didn't like nerf.

**Comment by aryst0krat** [comment]
Yeah if this was already possible before there's no reason for it to not be configurable. But for anyone out there with the ability to change configs anyway, you can probably just cheat in an empty Creative Tank from Mekanism and it essentially voids it too.

**Comment by haniura** [comment]
@LuciusV I changed a piece of mod code and compiled it. You can now use trash cans to dispose of nuclear waste. Currently for versions 1.19-1.19.2. If the owner of the mod (@SuperMartijn642 ) allows, I can send you a modified version. If you want, we can also modify it to the version you want. A very simple modification.

**Comment by SuperMartijn642** [comment]
I had some time available, so I just added it as a config option now.
It is available in version 1.0.17a for Minecraft 1.16, 1.18, and 1.19.

**Comment by haniura** [comment]
oh, nice, so i can remove my recompiled file... But thanks
