### ISSUE TITLE
[Crash] 1.19.2 Crash When Placing Fluid/Ultimate Trash Cans

### ISSUE THREAD

**Issue by enigmaquip** [SuperMartijn642/TrashCans#19]
**Version Info**
- Minecraft, 1.19.2
- Trash Cans, 1.0.15a
- Core lib, 1.0.19a

**Steps to Reproduce**
With Mekanism installed, place down a trash can that handles Gasses (Fluid or Ultimate)

**Crash report (~/logs/latest.log)**
https://mclo.gs/y9yMjzQ

```
java.lang.NoSuchFieldError: GAS_HANDLER_CAPABILITY
	at com.supermartijn642.trashcans.compat.mekanism.MekanismCompatOn.getGasHandlerCapability(MekanismCompatOn.java:33) ~[trashcans-1.0.15a-forge-mc1.19.jar%23264!/:?] {re:classloading}
```
Looks like the capability was renamed to just `GAS_HANDLER`
<https://github.com/mekanism/Mekanism/blob/1.19.x/src/main/java/mekanism/common/capabilities/Capabilities.java>

**Comment by SuperMartijn642** [comment]
Whoops, I was still using the 1.18 version of Mekanism to compile against until it released for 1.19.
I fixed it now in Trash Cans 1.0.15b for 1.19.

Thank you for reporting the issue!
