### ISSUE TITLE
[Question] Whitelisting items?

### ISSUE THREAD

**Issue by Smilelikejoker** [SuperMartijn642/TrashCans#21]
**Question**
I'm trying to figure out how to whitelist.  The only setting the trashcans have is blacklist.  Is whitelisting still possible?

I'm trying to use the trashcan as filter to destroy the junk I don't want while letting the filtered items pass through to a hopper.

**Comment by ResaloliPT** [comment]
i think this is related to the bug #22, currently on modpack Direwolf20 1.19, im having this problem, also saw other reports including ATM 8, checked with other friends and they also have the same problem on 1.19

**Comment by SuperMartijn642** [comment]
Fixed in version 1.0.16.
