### ISSUE TITLE
[Bug] Blacklist/Whitelist toggle in the UI isnt working in 1.19.2

### ISSUE THREAD

**Issue by Saereth** [SuperMartijn642/TrashCans#22]
**Version Info**
- Minecraft 1.19.2 
- Trash Cans, trashcans-1.0.15b-forge-mc1.19
- Core lib, supermartijn642corelib-1.0.19a-forge-mc1.19

**Description of the Bug**
The blacklist toggle in the UI makes a click sound when pressed but doesn't seem to actually invert the filter

**Steps to Reproduce**
make a trash can, put stone in the filter, click the blacklist toggle

**Screenshots**
![image](https://user-images.githubusercontent.com/9200909/201970134-96e89447-ec25-4a64-a18f-5d9eb81262b2.png)

**Comment by notFalkon** [comment]
I'm also having this issue

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.0.16.

Thank you for reporting the issue!
