### ISSUE TITLE
[Question] Compiling

### ISSUE THREAD

**Issue by haniura** [SuperMartijn642/TrashCans#28]
**Question**
...

How can i compile this mod? i dont have package com.supermartijn642.core

**Comment by SuperMartijn642** [comment]
In the `build.gradle` file, swap the current core library line with the one that's commented out. It should look like this:
```diff
- // implementation fg.deobf("curse.maven:supermartijn642s-core-lib-454372:${project.core_library_file}")
- implementation fg.deobf("com.supermartijn642:supermartijn642corelib:1.1.0-forge-mc1.15")
+ implementation fg.deobf("curse.maven:supermartijn642s-core-lib-454372:${project.core_library_file}")
+ // implementation fg.deobf("com.supermartijn642:supermartijn642corelib:1.1.0-forge-mc1.15")
```
Then in the `gradle.properties` file, replace the `core_library_file` property with the id for the latest file on CurseForge for whichever Minecraft version you're using here: https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib/files

That should do the trick 🙂
