### ISSUE TITLE
[Bug] Missing models

### ISSUE THREAD

**Issue by Oasis951** [SuperMartijn642/TrashCans#29]
- Minecraft, 1.18.2
- Trash Cans, trashcans-1.0.17-fabric-mc1.18.jar
- Core lib, Fabric - 0.14.19

Trash Cans have no texture in inventory or when placed down.

Place trash can down or look at them in inventory (or Just Enough Items Menu)

![Screenshot 2023-04-20 185453](https://user-images.githubusercontent.com/107067092/233448833-4ffac581-d298-4571-809b-c734b76dcdbe.png)
![Screenshot 2023-04-20 185528](https://user-images.githubusercontent.com/107067092/233448880-db53d695-7ddc-43ea-8982-437106b85e17.png)

**Comment by SuperMartijn642** [comment]
Appears to be working fine if I use just Trash Cans and its dependencies.
![image](https://user-images.githubusercontent.com/12382965/233482738-6f9d2d10-cc8b-42d4-9c34-9c62db048a36.png)

You seem to be using other mods, could you narrow down the mods needed to reproduce the issue? Also, could you share the `~/logs/latest.log` file from when this happens?

**Comment by Oasis951** [comment]
Apart from various performance mods and JEI, the only mods that I can think of are the ones that have furniture in them. These include:

Another Furniture (Starfish_Studios), BetterEnd and BetterNether (Quiqueck), Farmer's Delight (NewHoryzon), Macaw's Furniture (sketch_makaw), The Twilight Forest (Benimatic) and all of Yungs mods. I have more than 100 mods (including performance boosting ones)

Here's the latest log:
[latest.log](https://github.com/SuperMartijn642/TrashCans/files/11292867/latest.log)

**Comment by SuperMartijn642** [comment]
The only thing I can see in the log is
> Block file not found: trashcans:item_trash_can

Which is not a vanilla error message, so some other mod is likely messing with it.

Just downloading that many mods would take ages. Could you narrow down the mods needed to reproduce the issue?

**Comment by Oasis951** [comment]
I managed to find out which mod was causing the issue. The mod is called "ThonkUtil" by Jab125 which is a library required to use the fabric port of the "Goblin Traders" mod by the same creator.

The version of "ThonkUtil" that I'm using is "thonkutil-2.14.1+1.18.jar" which is the latest release for 1.18.2 of Minecraft. I'm using Fabric 0.14.19 as well.

**Comment by SuperMartijn642** [comment]
I cannot reproduce this, the models seem to work fine with ThonkUtil 2.14.1+1.18 installed.

**Comment by Oasis951** [comment]
I recreated a new profile on the curse forge app and tried it again with only the Trash cans mod (and your core lib mod) alongside ThonkUtil 2.14.1+1.18. The models are still missing
![Screenshot 2023-05-04 161211](https://user-images.githubusercontent.com/107067092/236251488-effce96a-0e5b-4433-bfaa-8e923bd02031.png)
![Screenshot 2023-05-04 160856](https://user-images.githubusercontent.com/107067092/236251510-7bbda2d5-d3d6-483e-a4f2-718c24d67b64.png)

Here's the latest log
[latest.log](https://github.com/SuperMartijn642/TrashCans/files/11398944/latest.log)

**Comment by SuperMartijn642** [comment]
Ah you are right. I originally only tested in the dev environment. If I load the exact same file in my dev environment it works fine, not sure why.

It seems to be an issue with ThonkUtil originally reported here https://github.com/LimeAppleBoat/ThonkUtil/issues/32. They assume every model has a '/' in there path.
They fixed it but only for 1.19. In 1.18 they break any model which is not in a subfolder.
Please report the issue to them.
