### ISSUE TITLE
1.16.4 Freezing

### ISSUE THREAD

**Issue by ghost** [SuperMartijn642/TrashCans#3]
**Version Info**
- Minecraft, ... 1.16.4
- Trash Cans, ...trashcans-1.0.4-mc1.16.4.jar

**Description of the Bug**
... minecraft total freeze

**Steps to Reproduce**
... place the ultimate trashcan and right click it - minecraft stops responding

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
It is fixed now in version 1.0.5.

Thanks for reporting the issue!
