### ISSUE TITLE
[Crash] Failing to find corelib dependency

### ISSUE THREAD

**Issue by jackhexed** [SuperMartijn642/TrashCans#38]
Minecraft 1.18.2
Trashcans 1.0.18-forge-mc1.18
Corelib 1.1.15-forge-mc1.18

**Steps to Reproduce**
Install the trashcans mod (through curseforge client, which automatically installs dependencies) and launch the game.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/TrashCans/files/13370809/latest.log)

**Comment by SuperMartijn642** [comment]
The CurseForge launcher sometimes doesn't download dependency files correctly. Please delete the core lib file from your mods folder and download it manually from the website

**Comment by jackhexed** [comment]
This worked, thank you <3
