### ISSUE TITLE
[Feature] Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [SuperMartijn642/TrashCans#4]
**Describe the solution you'd like**
- Waterlogging for all trash cans. This could provide for underwater decorations.

**Comment by SuperMartijn642** [comment]
I like the suggestion and I'll have a look at if I can implement it.

**Comment by SuperMartijn642** [comment]
I added the ability to waterlog the trash cans now in version 1.0.6.

Thanks for the suggestion!

**Comment by WenXin20** [comment]
Awesome, thanks!
