### ISSUE TITLE
[Crash] Trash cans causing crash/disconnect(?)

### ISSUE THREAD

**Issue by WhitePhant0m** [SuperMartijn642/TrashCans#45]
**Version Info**
- Minecraft, 1.21
- Trash Cans, 1.0.18
- Core lib, 1.1.17+c

**Steps to Reproduce**
(This is what the player said they did)
Placed down a trash can
Put wheat seeds in it
Crash/Disconnect

**Crash report (~/logs/latest.log)**
The [error](https://mclo.gs/iFm3ank)
[Latest.log](https://mclo.gs/8XwQVHO#L1122)

**Comment by Mark2-0** [comment]
- Minecraft 1.21
- NeoForge version 21.0.134-beta
- Trash Cans 1.0.18


Similar crash, similar steps. Happened to myself.
Placed down fluid trash can
Tried to shift clicked a bucket full of honey into it
Crash/Disconnect and now can't log back into that server

Crash report
https://mclo.gs/zp094CQ

**Comment by Uncraftbar** [comment]
Same thing with the trash cans, but also happening with the item collectors mod. put something in filter, crash and cant connect back to server.

**Comment by SuperMartijn642** [comment]
This is likely specific to servers as it worked fine in single player when I tested it. I am currently on vacation, so any fixes will have to wait until I am back in about a week from now.

**Comment by GanerCodes** [comment]
can confirm, can't log into my server now lol
![image](https://github.com/user-attachments/assets/e19178f7-30f8-4d15-8e01-92dc1dd54906)

**Comment by Saereth** [comment]
Can confirm this is still an issue on servers in 1.21.0/1.21.1, trying to set a whitelist will cause the issue as well and the player can basically never reconnect then. Not sure if this is the SAME issue or just related, if you would like a separate issue I can do that. Logl: https://mclo.gs/wKCz5Xc

**Comment by SuperMartijn642** [comment]
This issue *should* be fixed now in version 1.1.17a/b/d (depending on modloader) of my core library.
If someone could confirm it, that would be appreciated 🙃

**Comment by GanerCodes** [comment]
confirmed working 😊

**Comment by SuperMartijn642** [comment]
Thanks, I will close the issue as fixed then.
Thank you all for reporting the issue!
