### ISSUE TITLE
[Bug] Trashcans don't accept Mekanism steam

### ISSUE THREAD

**Issue by TheBedrockMaster** [SuperMartijn642/TrashCans#48]
**Version Info**
- Minecraft: 1.21.1
- Trash Cans: 1.0.18b
- Core lib: 1.1.17i

**Description of the Bug**
Fluid and Ultimate Trash Cans don't accept Mekanism Steam.

This was reported to ATM10 in https://github.com/AllTheMods/ATM-10/issues/152. Please let me know if it's an issue with ATM10.

**Comment by SuperMartijn642** [comment]
This seems to work fine.

https://github.com/user-attachments/assets/996acd40-295c-4b00-bf85-53763827648a
