### ISSUE TITLE
[Bug] Mekanism Radioactive Materials are possible to void

### ISSUE THREAD

**Issue by MuteTiefling** [SuperMartijn642/TrashCans#5]
**Version Info**
- Minecraft, 1.16.4
- Trash Cans, trashcans-1.0.6-mc1.16.4

**Description of the Bug**
Mekanism's radioactive materials (Nuclear Waste, Spent Nuclear Waste, Plutonium, and Polonium) are not meant to be voided. Breaking pipes with these materials in them irradiates the world. They are not allowed in Chemical tanks either and breaking machines with them also irradiates the world.

This is a design choice of Mekanism and ought to be respected by mods that interface with it. By allowing these to be voided, it very much removes the challenge of dealing with nuclear products. 

#2 introduced gas support, but did not introduce any blacklist that I'm seeing. 

**Steps to Reproduce**

Pipe any of these fluids into your trash cans and they go away without leaving radiation. Ideally, they simply shouldn't go in. 

**Screenshots**

**Comment by MuteTiefling** [comment]
For what it's worth, Mekanism tanks do already void the gases that are allowed to be voided (most of them). So while it's cool to have an extra way to do it, this isn't strictly required either.

**Comment by SuperMartijn642** [comment]
I didn't even know Mekanism has radioactive materials. I will make sure to change it so trash cans don't accept them.
Is it just gasses or also items and liquids that shouldn't be voided?

**Comment by MuteTiefling** [comment]
It's only those 4 gases.

**Comment by SuperMartijn642** [comment]
I blocked any gasses that are radioactive now, so hopefully that also works if Mekanism ever adds new ones. I fixed it in 1.0.6a for all the 1.16 versions.

Thank you for reporting the issue and the excellent instructions!

**Comment by MuteTiefling** [comment]
Awesome! Thanks for the quick fix!

**Comment by SirDenchik** [comment]
i hope this will become configurable cause i hate because how you intent on doing it originally

**Comment by SuperMartijn642** [comment]
This is a design choice by Mekanism. Radioactive material is not intended to be voidable.
