### ISSUE TITLE
[Feature-1.16.5] gas trash can

### ISSUE THREAD

**Issue by EnterFor** [SuperMartijn642/TrashCans#8]
**Is your feature request related to a problem? Please describe.**
I hope you add a gas trash can, it will be very useful.

**Describe the solution you'd like**
I hope you add a gas trash can, it will be very useful.

**Comment by SuperMartijn642** [comment]
The liquid trash can can already filter and void gasses. I don't think adding it as a separate block will be very useful.

**Comment by EnterFor** [comment]
In my test, gas cannot enter the trash can
Test using gas in MEK

**Comment by SuperMartijn642** [comment]
I can void gasses just fine when testing.
What exactly are you trying to do?

**Comment by Robball14** [comment]
if you mean Mekanism, the mod already has its own way to dump his gasses, just set the gas tank to "dump"

**Comment by SuperMartijn642** [comment]
No I meant:
What did @EnterFor try, to test if the gas trash can works?

For me gas can just be voided using the liquid trash can, so I don't see an issue.

**Comment by pupnewfster** [comment]
This [line](https://github.com/SuperMartijn642/TrashCans/blob/1.16.4/src/main/java/com/supermartijn642/trashcans/compat/mekanism/MekanismCompatOn.java#L83) should probably be changed to:
```java
if (!ChemicalAttributeValidator.process(gasStack, ChemicalAttributeValidator.DEFAULT))
    return false;
```
to ensure that any of our gases that require special compat cannot be voided, not just ones with radiation. I believe radiation is the only one that currently is marked as needing special handling/validation, but still...

**Comment by EnterFor** [comment]
I'm sorry for the late reply.
Yes, nuclear waste can't go into the trash can when I test it.

**Comment by SuperMartijn642** [comment]
@pupnewfster thanks I will change that!

@EnterFor I guess this issue can be closed then?
